id: "436657c6-a770-4958-9b58-61677db9514e"
name: "Client Initiated Account Linking"
triggers:
	- "POST_LOGIN"
useCases:
	- 
public: true
description: "Allows for a client initiated request to link to another account"
version: "1.0.0"
runtime: "node22"
sourceUrl: "https://github.com/auth0/opensource-marketplace/tree/main/templates/client-initiated-account-linking-POST_LOGIN/manifest.yaml"
notes: |
      **Required Secrets**

        *  - `AUTH0_DOMAIN` The Auth0 domain for the tenant, this is used to obtain the JWKS
        *  - `AUTH0_CLIENT_ID` Client ID for Regular Web Applicaton, this action is registered to
        *  - `AUTH0_CLIENT_SECRET` Client Secret for Regular Web Application, this action is registered to
        *  - `ACTION_SECRET` A secret that is unique to this application you can use `uuidgen` or a secure random string
        *
        * ## Optional Secrets and Configuration
        *
        *  - `ALLOWED_CLIENT_IDS` Comma Separated List of all client ids, by default all clients may request when using OIDC
        *  - `DEBUG` `debug` compatible string, this action uses `account-linking:{info,error,verbose}` to differentiate between logs
        *  - `ENFORCE_MFA` - if set to "yes" will require MFA to have been performed on the current session. Default: "yes"
        *  - `ENFORCE_EMAIL_VERIFICATION` - if set to "yes" will require the `primary` account's email is verified. Default: "yes"
        *  - `PIN_IP_ADDRESS` - If set to "yes" will require the transaction complete on same IP Address, this can be finnicky for some customers. Default: "no"

secrets:
	- label: 'AUTH0_DOMAIN'
	  defaultValue: ''
	- label: 'AUTH0_CLIENT_ID'
	  defaultValue: ''
	- label: 'AUTH0_CLIENT_SECRET'
	  defaultValue: ''
	- label: 'ACTION_SECRET'
	  defaultValue: ''

modules:
	- name: 'auth0'
	  version: 'latest'
	- name: 'openid-client'
	  version: 'latest'
	- name: 'jose'
	  version: 'latest'
	- name: 'debug'
	  version: 'latest'
	- name: '@panva/hkdf'
	  version: 'latest'
